version: '3.4'

services:
  fraternity-api:
    image: fraternity-api
    volumes:
        - ./:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 7001:7001
  
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --quiet
    volumes: 
      - ./mongo:/data/db
    ports: 
      - "27017:27017"



volumes:
  fraternity-api:
  mongo: