version: '3.4'

services:
  fraternityapi:
    image: fraternity-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 7001:7001
